version: '2'
volumes: 
  influxdb:
  grafana:
  nodered:
services:
  mosquitto:
    build: ./mosquitto
  influxdb:
    build: ./influxdb
    environment: 
      - 'INFLUXDB_DB=iotlab'
    volumes:
      - 'influxdb:/var/lib/influxdb'
    expose:
      - '8086'
  grafana:
    build: ./grafana
    depends_on:
      - influxdb
    volumes:
      - 'grafana:/var/lib/grafana'
    expose:
      - '3000'
  nodered:
    build: ./nodered
    depends_on:
      - influxdb
    volumes:
      - 'nodered:/var/lib/node-red'
    ports: 
      - '80:80'
