version: '2'
volumes: 
  influxdb:
  grafana:
  nodered:
services:
  mosquitto:
    build: ./mosquitto
    ports:
      - "1883:1883"
  influxdb:
    image: arm64v8/influxdb:latest
    environment: 
      - 'INFLUXDB_DB=iotlab'
    volumes:
      - 'influxdb:/var/lib/influxdb'
    ports:
      - '8086:8086'
  grafana:
    build: ./grafana
    depends_on:
      - influxdb
    volumes:
      - 'grafana:/var/lib/grafana'
    ports:
      - '3000:3000'
  nodered:
    build: ./nodered
    depends_on:
      - influxdb
    volumes:
      - 'nodered:/var/lib/node-red'
    ports: 
      - '80:80'
